import { 
  MessageCircle, Users, Instagram, Skull, Crown, Music, Gamepad2, Film, 
  BookOpen, Heart, Zap, Globe, Youtube, Twitter, Link2, Star, Flame, 
  Ghost, Sword, Shield, Target, Rocket, Camera, Phone, Mail, MapPin,
  Calendar, Clock, Gift, Award, Trophy, Flag, Bookmark, Bell, Lock,
  Unlock, Key, Eye, EyeOff, Volume2, Mic, Video, Image, FileText,
  Folder, Download, Upload, Share2, Send, MessageSquare, ThumbsUp,
  Smile, Coffee, Pizza, Beer, Cigarette, Pill, Syringe, Sparkles,
  Moon, Sun, Cloud, Umbrella, Snowflake, Droplet, Wind, Wifi,
  Bluetooth, Battery, Cpu, Monitor, Smartphone, Tablet, Watch,
  Headphones, Speaker, Radio, Tv, Laptop, Mouse, Keyboard, Printer,
  LucideIcon
} from "lucide-react";

export const iconOptions: { name: string; icon: LucideIcon }[] = [
  { name: "Users", icon: Users },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Instagram", icon: Instagram },
  { name: "Skull", icon: Skull },
  { name: "Crown", icon: Crown },
  { name: "Music", icon: Music },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Film", icon: Film },
  { name: "BookOpen", icon: BookOpen },
  { name: "Heart", icon: Heart },
  { name: "Zap", icon: Zap },
  { name: "Globe", icon: Globe },
  { name: "Youtube", icon: Youtube },
  { name: "Twitter", icon: Twitter },
  { name: "Link2", icon: Link2 },
  { name: "Star", icon: Star },
  { name: "Flame", icon: Flame },
  { name: "Ghost", icon: Ghost },
  { name: "Sword", icon: Sword },
  { name: "Shield", icon: Shield },
  { name: "Target", icon: Target },
  { name: "Rocket", icon: Rocket },
  { name: "Camera", icon: Camera },
  { name: "Phone", icon: Phone },
  { name: "Mail", icon: Mail },
  { name: "MapPin", icon: MapPin },
  { name: "Calendar", icon: Calendar },
  { name: "Clock", icon: Clock },
  { name: "Gift", icon: Gift },
  { name: "Award", icon: Award },
  { name: "Trophy", icon: Trophy },
  { name: "Flag", icon: Flag },
  { name: "Bookmark", icon: Bookmark },
  { name: "Bell", icon: Bell },
  { name: "Lock", icon: Lock },
  { name: "Unlock", icon: Unlock },
  { name: "Key", icon: Key },
  { name: "Eye", icon: Eye },
  { name: "EyeOff", icon: EyeOff },
  { name: "Volume2", icon: Volume2 },
  { name: "Mic", icon: Mic },
  { name: "Video", icon: Video },
  { name: "Image", icon: Image },
  { name: "FileText", icon: FileText },
  { name: "Folder", icon: Folder },
  { name: "Download", icon: Download },
  { name: "Upload", icon: Upload },
  { name: "Share2", icon: Share2 },
  { name: "Send", icon: Send },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "ThumbsUp", icon: ThumbsUp },
  { name: "Smile", icon: Smile },
  { name: "Coffee", icon: Coffee },
  { name: "Pizza", icon: Pizza },
  { name: "Beer", icon: Beer },
  { name: "Cigarette", icon: Cigarette },
  { name: "Pill", icon: Pill },
  { name: "Syringe", icon: Syringe },
  { name: "Sparkles", icon: Sparkles },
  { name: "Moon", icon: Moon },
  { name: "Sun", icon: Sun },
  { name: "Cloud", icon: Cloud },
  { name: "Umbrella", icon: Umbrella },
  { name: "Snowflake", icon: Snowflake },
  { name: "Droplet", icon: Droplet },
  { name: "Wind", icon: Wind },
  { name: "Wifi", icon: Wifi },
  { name: "Bluetooth", icon: Bluetooth },
  { name: "Battery", icon: Battery },
  { name: "Cpu", icon: Cpu },
  { name: "Monitor", icon: Monitor },
  { name: "Smartphone", icon: Smartphone },
  { name: "Tablet", icon: Tablet },
  { name: "Watch", icon: Watch },
  { name: "Headphones", icon: Headphones },
  { name: "Speaker", icon: Speaker },
  { name: "Radio", icon: Radio },
  { name: "Tv", icon: Tv },
  { name: "Laptop", icon: Laptop },
  { name: "Mouse", icon: Mouse },
  { name: "Keyboard", icon: Keyboard },
  { name: "Printer", icon: Printer },
];

export const getIconComponent = (iconName: string): LucideIcon => {
  const found = iconOptions.find((opt) => opt.name === iconName);
  return found?.icon || Link2;
};
